### ISSUE TITLE
The Twitter Developers Page is Blank

### ISSUE THREAD

**Issue by kyle-jorve** [twitterdev/Twitter-API-v2-sample-code#90]
**Describe the bug**
When I go to the Twitter Developers page (https://developer.twitter.com/en/portal/petition/essential/basic-info), it's just blank.

**Comment by andypiper** [comment]
This is possibly related to [this current issue](https://api.twitterstat.us/incidents/77gr5nnc82nb) from the status page.

Please use our [Developer Forums](https://twittercommunity.com/) for questions like this, rather than GitHub Issues - this is not directly related to the code in this repository.
